### ISSUE TITLE
NLM -> JATS

### ISSUE THREAD

**Issue by egh** [PLOS/rich_citations_processor#5]
NLM is officially called "JATS" (http://jats.nlm.nih.gov/), we should probably change references to NLM generally.

**Comment by marcrohloff** [comment]
Even though the document type (DTD) is called NLM?

**Comment by egh** [comment]
Around PLOS people seem more likely to call it JATS than NLM DTD. Don't ask me why.

**Comment by egh** [comment]
"The current standard is NISO JATS version 1.0 and is fully backward compatible with NLM version 3.0."
